Do not set KeepAlive for non TCP connections
vbatoufflet/go-livestatus pull request #10
Opened 2018-06-27 16:30 UTC by riton

With the latest version of `master`, when using a _Unix socket_ to communicate with Livestatus, we face the following error:

```
2018/06/27 18:24:26 http: panic serving 127.0.0.1:56098: interface conversion: net.Conn is *net.UnixConn, not *net.TCPConn
goroutine 18 [running]:
net/http.(*conn).serve.func1(0xc4200e8c80)
        /opt/go/src/net/http/server.go:1721 +0xd0
panic(0x694f40, 0xc420070900)
[...]
```

This is due to the unconditional cast to a `*net.TCPConn` object in `client.go`.

This patch has been tested and fixes the issue.

2018-06-27 16:40 UTC, vbatoufflet requested changes
Thanks! Indeed, I didn't check it using a UNIX socket for a while. Sorry for that.

I just made a few comments to your PR.

2018-06-27 16:40 UTC, vbatoufflet commented on client.go
> +				break
`break` is not needed in Go at the end of case blocks. Could you please remove them?

2018-06-27 16:40 UTC, vbatoufflet commented on client.go
> +			default:
I think the `default` block is not mandatory either.

2018-06-27 17:30 UTC, riton commented
I've made the requested changes and pushed force.
I didn't know that `break` were optional in _go_, thanks !

2018-06-28 06:00 UTC, vbatoufflet approved these changes

2018-06-28 06:00 UTC, merged

2018-06-28 06:00 UTC, vbatoufflet commented
Just merged your PR. Thanks for the fix!