Make query errors more useful
vbatoufflet/go-livestatus pull request #13
Opened 2019-02-08 11:59 UTC by hekmon

Hello,

First thank you for your library, it has been really useful.

While debugging an issue we had, which was a concurrent workers access on the socket, we had a hard time figuring out why the parsing failed. So we:
* prefixed a bunch of errors to increase the level of details
* added a new error type capable of returning not only the error message but also the data and buffer currently in use when the error occurred. It does not break anything as the type implements the error interface, just add a way to get more. For example:
```go
[...]
resp, err := c.liveclient.Exec(c.networkQuery)
	if err != nil {
		if typedError, ok := err.(livestatus.ParseError); ok {
			c.logger.Debugf("[Livestatus] network request failed: %v | Failed data: '%s' | Buffer: '%s'",
				typedError.Message, typedError.FailedData, typedError.Buffer)
		}
		err = fmt.Errorf("error while executing network request: %v", err)
		return
	}
	if resp.Status != 200 {
[...]
```

2019-02-15 07:18 UTC, vbatoufflet requested changes
Hi @hekmon,

It's a nice idea, thanks for the PR. It's always useful to have more context when debugging issues.

Could you please make all your error messages looking like “failed to…”? Indeed, some start with “failed”, other ones ends with failed. It's just for consistency :)

2019-02-15 10:02 UTC, hekmon commented
I guess we were too eager to get to the bottom of our bug ;) Fixed !

2019-02-18 06:46 UTC, vbatoufflet approved these changes

2019-02-18 06:48 UTC, merged

2019-02-18 06:48 UTC, vbatoufflet commented
LGTM 👍

Thanks again for your PR.